### ISSUE TITLE
[bug report]  Many RSpec's examples was failed by bad URI

### ISSUE THREAD

**Issue by sachin21** [kufu/kiji#4]
I executed `bundle exec rspec` after `bundle install`. So many RSpec's was failed by bad URI
```
      URI::InvalidURIError:
        bad URI(is not URI?): https://<EGOV-SOFTWARE-ID>:<EGOV-BASIC-AUTH-PASSWORD>@api2.kn.e-gov.go.jp/shinsei/1/access/payment/9002015000243934
```
I think fixture's `http_interactions.request.uri` has a syntax error for Ruby's URI module.

How did you testing examples with RSpec? If you mind, could you write here?

**Comment by kakipo** [comment]
You have to create `.env` file to run specs.

```
EGOV_BASIC_AUTH_ID=xxxxxxxxx
EGOV_BASIC_AUTH_PASSWORD=xxxxxxxxx
EGOV_SOFTWARE_ID=xxxxxxxxx
EGOV_API_END_POINT=xxxxxxxxx
EGOV_TEST_USER_ID=xxxxxxxxx
```

I'll check this out later.

**Comment by sachin21** [comment]
I see. Thank you for your reply.
